### ISSUE TITLE
Check averaging change please

### ISSUE THREAD

**Issue by vizowl** [nzherald/nz-election-prediction#1]
https://github.com/nzherald/nz-election-prediction/blob/a8ecff712012878bfd91f0ba3d6468d791c83d62/per-poll-simulations/common/Election-Simulation-pre-ME-Polls.R#L113

@wund525 @kamal-hothi I switched this from using polls less than 94 days prior to the election to the last 5 (or less) polls. But I may have misunderstood the intent of the code

**Comment by wund525** [comment]
Hi Chris, the intent of this code is to use all polls released in approximately the last 3 months before the election. I gave the polls not to be used the arbitrary release data of 100 so if you switch it to a filter of less than 100 days that'd be great

**Comment by vizowl** [comment]
Thanks Wil

We are just trying to run the year before the election of polls as if the model was run on the day it was released. 

So if that case should it still be the polls from 100 days before the election? That will be no polls for many of the runs? That is why I took the last five...

Cheers 
Chris

**Comment by wund525** [comment]
sorry I'm a little confused - do you want to have a weighted average for every day for the year before the election?

If this is the case you can just change the filter so that it filters on days before rather than release date and set it at 365.

There issue here is that I did not optimise over those parameters so that it may not be wholly accurate. 

Also you would not be able to include those additional polls in the simulations because I did not optimise over them and they would decrease uncertainty to an undesirable extend since the code estimates the SD function relies on log(number of polls) i.e. you would need to switch back to the original code for simulations.

Two other solutions would be (for the dates before the current model starts estimating the polling average) either:
1. use a five point moving average - or some other number
2. use the gam smoothed curve but with the data frame filtered to polls to that day i.e. filter to polls 365 and then get predicted value until the next polling date, then refit gam with new poll etc.
^ A cheat way could be just to filter to the last poll before we switch to the other method and just use that curve (technically this isn't right but would be close enough)

Please let me know if you want any clarification

Wil

**Comment by vizowl** [comment]
Thanks Wil

We are actually trying to produce a time series of estimates - one for each poll in the last year as it was released. But I think your recommendations hold. I'm not sure if I'll actually be able to make them work but we will see.

**Comment by wund525** [comment]
Ahh okay - in that case I would certainly recommend just using the gam smoother as the value

So rather than saving trendline adjustment save rnorm(Muu, SE) - and replace the weighted average+trendadj term in the adjustedaverage function with that

Also for the SD term in the adjusted average I'd set the log number polls to something like log(3) just because its so far away

Not the best but it's probably a reasonable approximation

**Comment by vizowl** [comment]
I just ping you with a code review comment for these changes - but I forgot
the log(3) bit ...

**Comment by vizowl** [comment]
I added that with dd3b7e6f521d8126b6297ffb4bec97342ebcf2c3 - how does it
look?

**Comment by wund525** [comment]
I commented on the other commit without seeing this. I'll look now

**Comment by wund525** [comment]
Perfect!

**Comment by vizowl** [comment]
Cool - I had to add the clip to zero back here
https://github.com/nzherald/nz-election-prediction/blob/master/per-poll-simulations/common/Election-Simulation-pre-ME-Polls.R#L162
 ...

**Comment by wund525** [comment]
Just added another clip to 0 in the other half of that if else - when daysto < 70

**Comment by vizowl** [comment]
Cool thanks

**Comment by wund525** [comment]
Closing because the issues (1) bubble is annoying me
